<?php

namespace Database\Seeders;

use App\Models\CalvingRecord;
use Illuminate\Database\Seeder;

class CalvingRecordsSeeder extends Seeder
{
    public function run()
    {
        // Clear existing records
        CalvingRecord::truncate();

        // Sept 2024 Records
        $recordsSept2024 = [
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Sept/2024',
                'operating_unit' => 'SKLIC BREEDLOT',
                'week' => 1,
                'calving_date' => '2024-09-06',
                'tag_no' => '5327',
                'sex' => 'MC',
                'colour' => 'Red',
                'dam_tag_no' => 'BF 23 3077',
                'location_block' => 'BL 1B',
                'location_phase' => null,
                'general_condition' => 'Good',
                'treatment_iodine' => true,
                'treatment_woundsarex' => true,
                'colostrum_feeding_24h' => true,
                'maminume' => true,
                'tagging_checklist_date' => '2024-09-07',
                'lcc_running_number' => '3179',
                'status' => 'issued',
                'issued_by_name' => 'Ahmad bin Ibrahim',
                'issued_by_unit' => 'SKFP - HOLDING YARD',
                'issued_by_signature' => true,
                'issued_at' => '2024-09-07 08:30:00',
            ],
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Sept/2024',
                'operating_unit' => 'SKLIC BREEDLOT',
                'week' => 1,
                'calving_date' => '2024-09-07',
                'tag_no' => '9565',
                'sex' => 'MC',
                'colour' => 'Honey',
                'dam_tag_no' => 'BF 23 2981',
                'location_block' => 'BL 1A',
                'location_phase' => null,
                'general_condition' => 'Good',
                'treatment_iodine' => true,
                'treatment_woundsarex' => true,
                'colostrum_feeding_24h' => true,
                'maminume' => true,
                'tagging_checklist_date' => '2024-09-08',
                'lcc_running_number' => '3180',
                'status' => 'verified',
                'issued_by_name' => 'Ahmad bin Ibrahim',
                'issued_by_unit' => 'SKFP - HOLDING YARD',
                'issued_by_signature' => true,
                'issued_at' => '2024-09-08 09:15:00',
                'verified_by_name' => 'Mohd Nazri bin Mohd Noor',
                'verified_by_unit' => 'SKFP - INTEGRATION',
                'verified_by_signature' => true,
                'verified_at' => '2024-09-08 10:00:00',
            ],
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Sept/2024',
                'operating_unit' => 'SKLIC BREEDLOT',
                'week' => 2,
                'calving_date' => '2024-09-08',
                'tag_no' => '5222',
                'sex' => 'MC',
                'colour' => 'Grey',
                'dam_tag_no' => 'B 12 6007',
                'location_block' => 'BL 1B',
                'location_phase' => null,
                'general_condition' => 'Good',
                'treatment_iodine' => true,
                'treatment_woundsarex' => true,
                'colostrum_feeding_24h' => true,
                'maminume' => true,
                'tagging_checklist_date' => '2024-09-09',
                'lcc_running_number' => '3181',
                'status' => 'witnessed',
                'issued_by_name' => 'Ahmad bin Ibrahim',
                'issued_by_unit' => 'SKFP - HOLDING YARD',
                'issued_by_signature' => true,
                'issued_at' => '2024-09-09 08:00:00',
                'verified_by_name' => 'Mohd Nazri bin Mohd Noor',
                'verified_by_unit' => 'SKFP - INTEGRATION',
                'verified_by_signature' => true,
                'verified_at' => '2024-09-09 09:30:00',
                'witnessed_by_name' => 'Shahrinizam bin Ishak',
                'witnessed_by_unit' => 'SKSSB SKSB / CENTRAL LAB',
                'witnessed_by_signature' => true,
                'witnessed_at' => '2024-09-09 14:00:00',
            ],
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Sept/2024',
                'operating_unit' => 'SKLIC BREEDLOT',
                'week' => 2,
                'calving_date' => '2024-09-12',
                'tag_no' => '4589',
                'sex' => 'FC',
                'colour' => 'Brown',
                'dam_tag_no' => 'BF 23 3102',
                'location_block' => 'BL 2A',
                'location_phase' => null,
                'general_condition' => 'Good',
                'treatment_iodine' => true,
                'treatment_woundsarex' => false,
                'colostrum_feeding_24h' => true,
                'maminume' => true,
                'tagging_checklist_date' => '2024-09-13',
                'lcc_running_number' => '3182',
                'status' => 'approved',
                'issued_by_name' => 'Ahmad bin Ibrahim',
                'issued_by_unit' => 'SKFP - HOLDING YARD',
                'issued_by_signature' => true,
                'issued_at' => '2024-09-13 08:00:00',
                'verified_by_name' => 'Mohd Nazri bin Mohd Noor',
                'verified_by_unit' => 'SKFP - INTEGRATION',
                'verified_by_signature' => true,
                'verified_at' => '2024-09-13 09:00:00',
                'witnessed_by_name' => 'Shahrinizam bin Ishak',
                'witnessed_by_unit' => 'SKSSB SKSB / CENTRAL LAB',
                'witnessed_by_signature' => true,
                'witnessed_at' => '2024-09-13 11:00:00',
                'approved_by_name' => 'Dr. Asrang Abdullah',
                'approved_by_unit' => 'SAWIT KINABALU LIVESTOCK INTEGRATED CENTRE',
                'approved_by_signature' => true,
                'approved_at' => '2024-09-13 15:00:00',
            ],
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Sept/2024',
                'operating_unit' => 'SKLIC BREEDLOT',
                'week' => 3,
                'calving_date' => '2024-09-15',
                'tag_no' => '7834',
                'sex' => 'MC',
                'colour' => 'Black',
                'dam_tag_no' => 'BF 23 3055',
                'location_block' => 'BL 3B',
                'location_phase' => null,
                'general_condition' => 'Fair',
                'treatment_iodine' => true,
                'treatment_woundsarex' => true,
                'colostrum_feeding_24h' => true,
                'maminume' => false,
                'tagging_checklist_date' => '2024-09-16',
                'lcc_running_number' => '3183',
                'status' => 'pending',
            ],
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Sept/2024',
                'operating_unit' => 'SKLIC BREEDLOT',
                'week' => 3,
                'calving_date' => '2024-09-18',
                'tag_no' => '6123',
                'sex' => 'FC',
                'colour' => 'Spotted',
                'dam_tag_no' => 'B 12 5890',
                'location_block' => 'BL 1A',
                'location_phase' => null,
                'general_condition' => 'Good',
                'treatment_iodine' => true,
                'treatment_woundsarex' => false,
                'colostrum_feeding_24h' => true,
                'maminume' => true,
                'tagging_checklist_date' => '2024-09-19',
                'lcc_running_number' => '3184',
                'status' => 'pending',
            ],
        ];

        // Aug 2024 Records
        $recordsAug2024 = [
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Aug/2024',
                'operating_unit' => 'SKLIC BREEDLOT',
                'week' => 1,
                'calving_date' => '2024-08-03',
                'tag_no' => '4892',
                'sex' => 'MC',
                'colour' => 'Chestnut',
                'dam_tag_no' => 'BF 23 2990',
                'location_block' => 'BL 1B',
                'location_phase' => null,
                'general_condition' => 'Good',
                'treatment_iodine' => true,
                'treatment_woundsarex' => true,
                'colostrum_feeding_24h' => true,
                'maminume' => true,
                'tagging_checklist_date' => '2024-08-04',
                'lcc_running_number' => '3150',
                'status' => 'approved',
                'issued_by_name' => 'Ahmad bin Ibrahim',
                'issued_by_unit' => 'SKFP - HOLDING YARD',
                'issued_by_signature' => true,
                'issued_at' => '2024-08-04 08:00:00',
                'verified_by_name' => 'Mohd Nazri bin Mohd Noor',
                'verified_by_unit' => 'SKFP - INTEGRATION',
                'verified_by_signature' => true,
                'verified_at' => '2024-08-04 09:00:00',
                'witnessed_by_name' => 'Shahrinizam bin Ishak',
                'witnessed_by_unit' => 'SKSSB SKSB / CENTRAL LAB',
                'witnessed_by_signature' => true,
                'witnessed_at' => '2024-08-04 11:00:00',
                'approved_by_name' => 'Dr. Asrang Abdullah',
                'approved_by_unit' => 'SAWIT KINABALU LIVESTOCK INTEGRATED CENTRE',
                'approved_by_signature' => true,
                'approved_at' => '2024-08-04 14:00:00',
            ],
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Aug/2024',
                'operating_unit' => 'SKLIC HOLDING YARD',
                'week' => 2,
                'calving_date' => '2024-08-10',
                'tag_no' => '3456',
                'sex' => 'FC',
                'colour' => 'White',
                'dam_tag_no' => 'BF 23 3100',
                'location_block' => 'HY 1A',
                'location_phase' => null,
                'general_condition' => 'Good',
                'treatment_iodine' => true,
                'treatment_woundsarex' => false,
                'colostrum_feeding_24h' => true,
                'maminume' => true,
                'tagging_checklist_date' => '2024-08-11',
                'lcc_running_number' => '3151',
                'status' => 'approved',
                'issued_by_name' => 'Salleh bin Yusof',
                'issued_by_unit' => 'SKFP - HOLDING YARD',
                'issued_by_signature' => true,
                'issued_at' => '2024-08-11 08:30:00',
                'verified_by_name' => 'Mohd Nazri bin Mohd Noor',
                'verified_by_unit' => 'SKFP - INTEGRATION',
                'verified_by_signature' => true,
                'verified_at' => '2024-08-11 10:00:00',
                'witnessed_by_name' => 'Shahrinizam bin Ishak',
                'witnessed_by_unit' => 'SKSSB SKSB / CENTRAL LAB',
                'witnessed_by_signature' => true,
                'witnessed_at' => '2024-08-11 13:00:00',
                'approved_by_name' => 'Dr. Asrang Abdullah',
                'approved_by_unit' => 'SAWIT KINABALU LIVESTOCK INTEGRATED CENTRE',
                'approved_by_signature' => true,
                'approved_at' => '2024-08-11 16:00:00',
            ],
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Aug/2024',
                'operating_unit' => 'SKLIC INTEGRATION',
                'week' => 4,
                'calving_date' => '2024-08-25',
                'tag_no' => '7788',
                'sex' => 'MC',
                'colour' => 'Tan',
                'dam_tag_no' => 'B 12 6100',
                'location_block' => 'INT 1',
                'location_phase' => null,
                'general_condition' => 'Good',
                'treatment_iodine' => true,
                'treatment_woundsarex' => true,
                'colostrum_feeding_24h' => true,
                'maminume' => true,
                'tagging_checklist_date' => '2024-08-26',
                'lcc_running_number' => '3155',
                'status' => 'approved',
                'issued_by_name' => 'Zulkefli bin Mat',
                'issued_by_unit' => 'SKFP - HOLDING YARD',
                'issued_by_signature' => true,
                'issued_at' => '2024-08-26 09:00:00',
                'verified_by_name' => 'Mohd Nazri bin Mohd Noor',
                'verified_by_unit' => 'SKFP - INTEGRATION',
                'verified_by_signature' => true,
                'verified_at' => '2024-08-26 10:30:00',
                'witnessed_by_name' => 'Shahrinizam bin Ishak',
                'witnessed_by_unit' => 'SKSSB SKSB / CENTRAL LAB',
                'witnessed_by_signature' => true,
                'witnessed_at' => '2024-08-26 14:30:00',
                'approved_by_name' => 'Dr. Asrang Abdullah',
                'approved_by_unit' => 'SAWIT KINABALU LIVESTOCK INTEGRATED CENTRE',
                'approved_by_signature' => true,
                'approved_at' => '2024-08-26 16:00:00',
            ],
        ];

        // Jul 2024 Records
        $recordsJul2024 = [
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Jul/2024',
                'operating_unit' => 'SKLIC BREEDLOT',
                'week' => 1,
                'calving_date' => '2024-07-05',
                'tag_no' => '2234',
                'sex' => 'MC',
                'colour' => 'Brindle',
                'dam_tag_no' => 'BF 23 2900',
                'location_block' => 'BL 2A',
                'location_phase' => null,
                'general_condition' => 'Good',
                'treatment_iodine' => true,
                'treatment_woundsarex' => true,
                'colostrum_feeding_24h' => true,
                'maminume' => true,
                'tagging_checklist_date' => '2024-07-06',
                'lcc_running_number' => '3120',
                'status' => 'approved',
                'issued_by_name' => 'Ahmad bin Ibrahim',
                'issued_by_unit' => 'SKFP - HOLDING YARD',
                'issued_by_signature' => true,
                'issued_at' => '2024-07-06 08:00:00',
                'verified_by_name' => 'Mohd Nazri bin Mohd Noor',
                'verified_by_unit' => 'SKFP - INTEGRATION',
                'verified_by_signature' => true,
                'verified_at' => '2024-07-06 09:00:00',
                'witnessed_by_name' => 'Shahrinizam bin Ishak',
                'witnessed_by_unit' => 'SKSSB SKSB / CENTRAL LAB',
                'witnessed_by_signature' => true,
                'witnessed_at' => '2024-07-06 11:00:00',
                'approved_by_name' => 'Dr. Asrang Abdullah',
                'approved_by_unit' => 'SAWIT KINABALU LIVESTOCK INTEGRATED CENTRE',
                'approved_by_signature' => true,
                'approved_at' => '2024-07-06 14:00:00',
            ],
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Jul/2024',
                'operating_unit' => 'SKLIC BREEDLOT',
                'week' => 2,
                'calving_date' => '2024-07-12',
                'tag_no' => '5567',
                'sex' => 'FC',
                'colour' => 'Red',
                'dam_tag_no' => 'BF 23 2950',
                'location_block' => 'BL 1B',
                'location_phase' => null,
                'general_condition' => 'Good',
                'treatment_iodine' => true,
                'treatment_woundsarex' => false,
                'colostrum_feeding_24h' => true,
                'maminume' => true,
                'tagging_checklist_date' => '2024-07-13',
                'lcc_running_number' => '3121',
                'status' => 'approved',
                'issued_by_name' => 'Ahmad bin Ibrahim',
                'issued_by_unit' => 'SKFP - HOLDING YARD',
                'issued_by_signature' => true,
                'issued_at' => '2024-07-13 08:00:00',
                'verified_by_name' => 'Mohd Nazri bin Mohd Noor',
                'verified_by_unit' => 'SKFP - INTEGRATION',
                'verified_by_signature' => true,
                'verified_at' => '2024-07-13 09:00:00',
                'witnessed_by_name' => 'Shahrinizam bin Ishak',
                'witnessed_by_unit' => 'SKSSB SKSB / CENTRAL LAB',
                'witnessed_by_signature' => true,
                'witnessed_at' => '2024-07-13 11:00:00',
                'approved_by_name' => 'Dr. Asrang Abdullah',
                'approved_by_unit' => 'SAWIT KINABALU LIVESTOCK INTEGRATED CENTRE',
                'approved_by_signature' => true,
                'approved_at' => '2024-07-13 14:00:00',
            ],
            [
                'company_name' => 'SAWIT KINABALU FARM PRODUCTS SDN BHD',
                'company_no' => '465571-P',
                'ownership' => 'Wholly owned by Sawit Kinabalu Sdn Bhd (Co. No. 403109-W)',
                'form_no' => 'FORM 1B',
                'mcc_no' => '00023',
                'month_year' => 'Jul/2024',
                'operating_unit' => 'SKLIC BREEDLOT',
                'week' => 3,
                'calving_date' => '2024-07-20',
                'tag_no' => '8890',
                'sex' => 'MC',
                'colour' => 'Grey',
                'dam_tag_no' => 'B 12 5950',
                'location_block' => 'BL 3A',
                'location_phase' => null,
                'general_condition' => 'Fair',
                'treatment_iodine' => true,
                'treatment_woundsarex' => true,
                'colostrum_feeding_24h' => false,
                'maminume' => true,
                'tagging_checklist_date' => '2024-07-21',
                'lcc_running_number' => '3122',
                'status' => 'approved',
                'issued_by_name' => 'Ahmad bin Ibrahim',
                'issued_by_unit' => 'SKFP - HOLDING YARD',
                'issued_by_signature' => true,
                'issued_at' => '2024-07-21 08:00:00',
                'verified_by_name' => 'Mohd Nazri bin Mohd Noor',
                'verified_by_unit' => 'SKFP - INTEGRATION',
                'verified_by_signature' => true,
                'verified_at' => '2024-07-21 09:00:00',
                'witnessed_by_name' => 'Shahrinizam bin Ishak',
                'witnessed_by_unit' => 'SKSSB SKSB / CENTRAL LAB',
                'witnessed_by_signature' => true,
                'witnessed_at' => '2024-07-21 11:00:00',
                'approved_by_name' => 'Dr. Asrang Abdullah',
                'approved_by_unit' => 'SAWIT KINABALU LIVESTOCK INTEGRATED CENTRE',
                'approved_by_signature' => true,
                'approved_at' => '2024-07-21 14:00:00',
            ],
        ];

        // Combine all records
        $allRecords = array_merge($recordsSept2024, $recordsAug2024, $recordsJul2024);

        foreach ($allRecords as $record) {
            CalvingRecord::create($record);
        }

        $this->command->info('Calving records seeded successfully!');
        $this->command->info('Total records: ' . count($allRecords));
        $this->command->info('  - Sept/2024: ' . count($recordsSept2024) . ' records');
        $this->command->info('  - Aug/2024: ' . count($recordsAug2024) . ' records');
        $this->command->info('  - Jul/2024: ' . count($recordsJul2024) . ' records');
    }
}
